version: '3.7'
services:
  app:
    image: ukeweb/styleguide_devtools:0.5.0
    container_name: styleguide_devtools
    command: sh -c "npm i && npm run hmr-watch"
    ports:
      - 9000:9000
    volumes:
      - ../styleguide:/app/node_modules/styleguide
